### ISSUE TITLE
    assert (glove_reader.vect_size == opts.embedding_size), "Embedding size mismatch"

### ISSUE THREAD

**Issue by johndpope** [p-kar/text-style-transfer-gan#5]
python main.py --batch_size 20 \
        --dataFile misc/shakespeare_original.h5 \
        --jsonFile misc/shakespeare_original.json \
        --shuffle True --train_mode pretrain_lm --embedding_size 300 \
        --hidden_size 350 --num_rnn_layers 1 --use_lstm True \
        --epochs 100 --lr 1e-4 --weight_decay 1e-4 \
        --dropout_p 0.5 --max_norm 10 \
        --log_dir logs/pretrain_lm/shakespear_formal \
        --num_sample_sents 5 \
        --save_path models/pretrain_lm/shakespear_formal --model_name model
======================= Parameters =======================
==========================================================
batch_size                    : 20
dataFile                      : misc/shakespeare_original.h5
jsonFile                      : misc/shakespeare_original.json
pdataFile                     : misc/shakespeare_modern.h5
pjsonFile                     : misc/shakespeare_modern.json
shuffle                       : True
train_mode                    : pretrain_lm
embedding_size                : 300
hidden_size                   : 350
num_rnn_layers                : 1
use_lstm                      : True
use_attention                 : True
epochs                        : 100
lr                            : 0.0001
weight_decay                  : 0.0001
dropout_p                     : 0.5
max_norm                      : 10.0
enable_scheduled_sampling     : False
scheduled_sampling_decay_type : linear
scheduled_sampling_decay_factor: 0.005
scheduled_sampling_min_eps    : 0.5
log_dir                       : logs/pretrain_lm/shakespear_formal
num_sample_sents              : 5
log_iter                      : 10
sent_sample_iter              : 50
save_path                     : models/pretrain_lm/shakespear_formal
model_name                    : model
pretrained_lm1_model_path     : ./models/shakespeare_formal_lm_best.net
pretrained_lm2_model_path     : ./models/shakespeare_informal_lm_best.net
pretrained_seq2seq_model_path : ./models/shakespeare_formal_informal.net
pretrained_glove_vector_path  : ./data/glove/glove.twitter.27B.200d.txt
use_glove_embeddings          : True
num_searches                  : 1
g_update_step_diff            : 25
d_update_step_diff            : 1
lr_ratio_D_by_G               : 1.0
discount_factor               : 0.99
lamda_rl                      : 1.0
lamda_rec_ii                  : 0.01
lamda_rec_ij                  : 0.001
lamda_cos_ij                  : 0.1
skip_weight_decay             : 0.995
freeze_embeddings             : True
clamp_lower                   : -0.01
clamp_upper                   : 0.01
d_pretrain_num_epochs         : 3
disc_recalibrate              : 100
g_update_step_diff_recalib    : 200

########################################################

Loading GloVe vectors from ./data/glove/glove.twitter.27B.200d.txt... done
Traceback (most recent call last):
  File "main.py", line 1470, in <module>
    main(opts)
  File "main.py", line 1385, in main
    pretrain_language_model(opts)
  File "main.py", line 132, in pretrain_language_model
    load_embedding_from_glove(opts, loader, embedding)
  File "main.py", line 110, in load_embedding_from_glove
    assert (glove_reader.vect_size == opts.embedding_size), "Embedding size mismatch"
AssertionError: Embedding size mismatch

**Comment by johndpope** [comment]
I got around this by changing embedding size to 200. I'm curious if there was a expansion or something to get glove to 300....... 


```python

def load_embedding_from_glove(opts, loader, embedding):
    glove_reader = GloveVec(opts.pretrained_glove_vector_path)
    print("glove_reader.vect_size:",glove_reader.vect_size)
    print("opts.embedding_size:",opts.embedding_size)
    
    assert (glove_reader.vect_size == opts.embedding_size), "Embedding size mismatch"
    embed_data = np.zeros((loader.vocab_size, opts.embedding_size), dtype=np.float64)
    for word in loader.vocab.keys():
        embed_idx = loader.vocab[word]
        embed_data[embed_idx, :] = glove_reader.get_vector(word)
    embedding.embedding.weight.data.copy_(torch.from_numpy(embed_data))
    del glove_reader

```
